### ISSUE TITLE
Preprocessing incorrectly using mask? 

### ISSUE THREAD

**Issue by joseph-bae** [MaastrichtU-CDS/hn_cnn#1]
Excuse me if I am making a mistake, but I am currently trying to reproduce some of your experiments. Looking at "image_preprocessing.py", I noticed that the process_scan() function seems to be using the CT slice with the largest tissue volume rather than using the GTV mask with the largest tumor volume. Specifically: 
`    scan = nib.load(scan_path) `
`    mask = nib.load(mask_path) `
`   # Check the Dicom information`
`    # print(img.header)`
`    scan_data = scan.get_fdata()`
`    pixels_by_slice = []`
`    # Select the slice to use (largest tumor area)`
`    for i in range(mask.shape[2]):`
`        scan_data_filter = np.where(`
`            scan_data[:, :, i] < min_interval, 0, scan_data[:, :, i]`
`        )`
`        pixels_by_slice.append(`
`            np.count_nonzero(np.where(scan_data_filter > max_interval, 0, scan_data_filter))`
`        )`
`    ct_slice_idx = np.argmax(pixels_by_slice)`

Here, the scan_data variable contains the CT scan and this code block specifically seems to be using values within the -50 and 300 pixel intensity range to define the slice with the maximum tumor burden. Shouldn't this be performed on the mask variable which should be binary and not require filtering between -50 and 300? This same code is replicated in window_cropping.py.

**Comment by pedro-cmat** [comment]
Hi Joseph, thanks for the feedback, indeed we wanted to select the slice with largest GTV area but also take into account the chosen HU window. In this script, it is assumed that the input CT scan has already been pre-processed with FSL (reoriented and mask applied) and thus only contains information within the GTV mask boundaries. We then apply the HU window when selecting the slice to pick the one with more information in this range. I've updated the documentation and the pre-processing script to better explain these choices.
